services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - "2003:5000"
    volumes:
      - /var/home/core/core-str/kavita/book:/book:Z
      - /var/home/core/core-str/kavita/config:/kavita/config:Z
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="true"