services:
  web:
    container_name: hoarder
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /var/home/core/core-str/hoarder/data:/data:z
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://hoarder-meilisearch:7700
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      DATA_DIR: /data
  chrome:
    container_name: hoarder_chrome
    image: ghcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    container_name: hoarder_meilisearch
    image: docker.io/getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /var/home/core/core-str/hoarder/meilisearch:/meili_data:z