server:
  assets-path: /app/assets

theme:
  light: true
  background-color: 220 23 95
  contrast-multiplier: 1.0
  primary-color: 220 91 54
  positive-color: 109 58 40
  negative-color: 347 87 44
  custom-css-file: /assets/user.css

branding:
  custom-footer: |
    <p>mizu</p>
  logo-url: /assets/logo.png
  favicon-url: /assets/logo.png

pages:
  !include: page_1.yml
  !include: page_2.yml
  !include: page_3.yml