services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - changedetection-data:/datastore
      environment:
        - PORT=5000
        - PUID=1000
        - PGID=1000
  #      - LOGGER_LEVEL=TRACE
        - BASE_URL=https://cd.mizu.reisen
        - HIDE_REFERER=true    
  #        Default number of parallel/concurrent fetchers
  #      - FETCH_WORKERS=10
  #        Absolute minimum seconds to recheck, overrides any watch minimum, change to 0 to disable
  #      - MINIMUM_SECONDS_RECHECK_TIME=3
  #        If you want to watch local files file:///path/to/file.txt (careful! security implications!)
  #      - ALLOW_FILE_URI=False
      ports:
        - 5000:5000
      restart: unless-stopped
     # Used for fetching pages via WebDriver+Chrome where you need Javascript support.
     # Now working on arm64 (needs testing on rPi - tested on Oracle ARM instance)
     # replace image with seleniarm/standalone-chromium:4.0.0-20211213
     
     # If WEBDRIVER or PLAYWRIGHT are enabled, changedetection container depends on that
     # and must wait before starting (substitute "browser-chrome" with "playwright-chrome" if last one is used)
#      depends_on:
#          playwright-chrome:
#              condition: service_started

    sockpuppetbrowser:
        hostname: sockpuppetbrowser
        image: dgtlmoon/sockpuppetbrowser:latest
        cap_add:
            - SYS_ADMIN
## SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
        restart: unless-stopped
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1024
            - SCREEN_DEPTH=16
            - MAX_CONCURRENT_CHROME_PROCESSES=10
volumes:
  changedetection-data: