services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /home/user/alpine_str/docker_vol/homepage:/app/config
      - /home/user/alpine_str/docker_vol/homepage/icon:/app/public/icons
      - /home/user/.docker/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1