services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - 'homepage:/app/config'
      - //home/user/.docker/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
volumes:
    homepage: {}